name: deep-tweezer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - conda=4.5.12=py36_1000
  - cython=0.29.2=py36hfc679d8_0
  - pip
  - numpy=1.19.5
  - jupyter=1.0.0
  - pip:
    - autopep8==1.3.5
    - datetime==4.3
    - imbalanced-learn==0.4.3
    - joblib==0.14.1     
    - matplotlib==2.2.3
    - pandas==0.22.0
    - pytest==4.0.1
    - python-dateutil==2.7.5
    - python-dotenv==0.9.1
    - requests==2.23.0     
    - scipy==1.4.1      
    - scikit-learn==0.21.0
    - seaborn==0.9.0
    - setuptools==40.6.3
    - statsmodels==0.9.0
    - tqdm==4.62.3
    - urllib3==1.25.9     
    - wheel==0.32.3
    - -e .