name: deep-tweezer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - conda=4.5.12=py36_1000
  - cython=0.29.2=py36hfc679d8_0
  - pip
  - numpy=1.19.5
  - jupyter=1.0.0
  - pip:
    - autopep8
    - datetime
    - gym
    - joblib     
    - matplotlib
    - pandas
    - pytest
    - python-dateutil
    - python-dotenv
    - scipy      
    - scikit-learn
    - seaborn
    - setuptools
    - statsmodels
    - tensorflow
    - tqdm
    - urllib3     
    - wheel
    - -e .
